# Generated by Django 5.2.15 on 2026-09-07 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publicreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicreview',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicreview',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='publicreview',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('other', 'Other approved source'), ('patient_portal', 'Patient review')], default='google', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='publicreview',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'patient_portal'), ('submitted_by__isnull', False)), fields=('submitted_by',), name='core_one_portal_review_per_user'),
        ),
    ]
