# Generated by Django 5.2.15 on 2026-09-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctorpagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpagecontent',
            name='credential_label_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorpagecontent',
            name='credential_label_en',
            field=models.TextField(blank=True),
        ),
    ]
