# Generated by Django 5.2.15 on 2026-09-16 08:47

import apps.core.content_validation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctorscheduleoverride'),
        ('core', '0005_doctorpagecontent_credential_label_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('text_ar', models.TextField(blank=True, max_length=6000, validators=[apps.core.content_validation.validate_public_text])),
                ('text_en', models.TextField(blank=True, max_length=6000, validators=[apps.core.content_validation.validate_public_text])),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=32)),
                ('title_ar', models.CharField(blank=True, max_length=180, validators=[apps.core.content_validation.validate_public_text])),
                ('title_en', models.CharField(blank=True, max_length=180, validators=[apps.core.content_validation.validate_public_text])),
                ('content_ar', models.TextField(blank=True, max_length=12000, validators=[apps.core.content_validation.validate_public_text])),
                ('content_en', models.TextField(blank=True, max_length=12000, validators=[apps.core.content_validation.validate_public_text])),
                ('presentation', models.CharField(choices=[('TEXT', 'Text'), ('LIST', 'List'), ('CHIPS', 'Chips'), ('CARDS', 'Cards')], default='LIST', max_length=5)),
                ('display_order', models.PositiveSmallIntegerField(default=90)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_sections', to='clinic.doctor')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('key', ''), _negated=True), fields=('doctor', 'key'), name='core_unique_builtin_doctor_section')],
            },
        ),
    ]
