# Generated by Django 5.2.15 on 2026-07-13 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_appointment_booking_app_doctor__2b7f9b_idx_and_more'),
        ('patients', '0002_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visit_reason', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True, help_text='Manual doctor/staff notes only. Do not store generated medical content.')),
                ('diagnosis_plan', models.TextField(blank=True, help_text='Manual diagnosis/plan written by doctor/staff only.')),
                ('instructions', models.TextField(blank=True, help_text='Manual instructions written by doctor/staff only.')),
                ('follow_up_notes', models.TextField(blank=True, help_text='Manual follow-up notes written by doctor/staff only.')),
                ('is_visible_to_patient', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_records', to='booking.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_records', to='patients.patient')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('short_video', 'Short video')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private_only', 'Private only'), ('visible_to_patient', 'Visible to patient'), ('approved_public_case', 'Approved public case')], db_index=True, default='private_only', max_length=30)),
                ('consent_confirmed', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_media', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='records.visitrecord')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('doctor_note', 'Doctor note'), ('staff_note', 'Staff note'), ('follow_up', 'Follow-up')], db_index=True, default='doctor_note', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(help_text='Manual doctor/staff note only. Do not store generated medical content.')),
                ('is_visible_to_patient', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='records.visitrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['patient', 'visit_date'], name='records_vis_patient_9802ea_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrecord',
            index=models.Index(fields=['patient', 'is_visible_to_patient'], name='records_vis_patient_ca7e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='recordmedia',
            index=models.Index(fields=['patient', 'uploaded_at'], name='records_rec_patient_933a05_idx'),
        ),
        migrations.AddIndex(
            model_name='recordmedia',
            index=models.Index(fields=['patient', 'visibility'], name='records_rec_patient_ccbb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='recordmedia',
            index=models.Index(fields=['visibility', 'consent_confirmed', 'is_active'], name='records_rec_visibil_de2be1_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordmedia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('visibility', 'approved_public_case'), _negated=True), ('consent_confirmed', True), _connector='OR'), name='record_media_public_case_requires_consent'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient', 'created_at'], name='records_cli_patient_75fdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient', 'is_visible_to_patient'], name='records_cli_patient_a58451_idx'),
        ),
    ]
