# Generated by Django 5.2.15 on 2026-07-14 00:18

import uuid

import apps.records.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_record_media_public_ids(apps, schema_editor):
    record_media_model = apps.get_model("records", "RecordMedia")
    for media in record_media_model.objects.filter(public_id__isnull=True).only("pk"):
        media.public_id = uuid.uuid4()
        media.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recordmedia",
            name="content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="recordmedia",
            name="file",
            field=models.FileField(
                default="",
                storage=apps.records.storage.PrivateMediaStorage(),
                upload_to=apps.records.storage.private_record_media_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="recordmedia",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recordmedia",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="recordmedia",
            name="public_id",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="recordmedia",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="record_media_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            populate_record_media_public_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="recordmedia",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
