# Generated by Django 5.2.15 on 2026-08-29 02:52

import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


ROLE_TITLE_PATTERN = re.compile(
    r"^\[\[public-case:(primary|before|after|video|video_cover)\]\](.*)$",
    re.DOTALL,
)


def decode_legacy_public_media(media_type, stored_title):
    """Return the stable migration-time role and a legitimate case title."""
    title = (stored_title or "").strip()
    match = ROLE_TITLE_PATTERN.match(title)
    if match:
        decoded_role = match.group(1)
        clean_title = match.group(2).strip()
        if media_type == "short_video":
            return "video", clean_title
        if decoded_role == "video_cover":
            return "video_cover", clean_title
        if decoded_role in {"before", "after"}:
            return decoded_role, clean_title
        return "primary", clean_title

    normalized = title.casefold()
    for marker, role in (
        ("before", "before"),
        ("قبل", "before"),
        ("after", "after"),
        ("بعد", "after"),
    ):
        if normalized == marker or normalized.startswith(f"{marker} "):
            return ("video" if media_type == "short_video" else role), ""

    if media_type == "short_video":
        return "video", title
    return "primary", title


def backfill_public_cases(apps, schema_editor):
    PublicCase = apps.get_model("records", "PublicCase")
    RecordMedia = apps.get_model("records", "RecordMedia")
    public_rows = list(
        RecordMedia.objects.filter(visibility="approved_public_case")
        .order_by("-uploaded_at", "-public_id", "-pk")
    )

    grouped_rows = {}
    group_order = []
    for media in public_rows:
        group_key = (
            ("visit", media.patient_id, media.visit_id)
            if media.visit_id
            else ("media", media.pk)
        )
        if group_key not in grouped_rows:
            grouped_rows[group_key] = []
            group_order.append(group_key)
        grouped_rows[group_key].append(media)

    for group_key in group_order:
        rows = grouped_rows[group_key]
        title = ""
        note = ""
        decoded_rows = []
        for media in rows:
            role, candidate_title = decode_legacy_public_media(
                media.media_type,
                media.title,
            )
            decoded_rows.append((media, role))
            if candidate_title and not title:
                title = candidate_title[:180]
            if media.description and not note:
                note = media.description

        first_media = rows[0]
        public_case = PublicCase.objects.create(
            patient_id=first_media.patient_id,
            reference_visit_id=first_media.visit_id,
            title=title,
            note=note,
            consent_confirmed=True,
            is_published=True,
            created_by_id=first_media.uploaded_by_id,
        )
        for media, role in decoded_rows:
            media.public_case_id = public_case.pk
            media.public_case_role = role
            media.save(update_fields=["public_case", "public_case_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_gender'),
        ('records', '0003_recordmediafolder_recordmedia_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('note', models.TextField(blank=True)),
                ('consent_confirmed', models.BooleanField(db_index=True, default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_cases_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_cases', to='patients.patient')),
                ('reference_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_cases', to='records.visitrecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='recordmedia',
            name='public_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_items', to='records.publiccase'),
        ),
        migrations.AddField(
            model_name='recordmedia',
            name='public_case_role',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('before', 'Before'), ('after', 'After'), ('video', 'Video'), ('video_cover', 'Video cover')], default='', max_length=20),
        ),
        migrations.RunPython(backfill_public_cases, migrations.RunPython.noop),
    ]
