# Generated by Django 5.2.15 on 2026-08-29 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_gender'),
        ('records', '0004_recordmedia_public_case_role_publiccase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recordmedia',
            name='record_media_public_case_requires_consent',
        ),
        migrations.AddConstraint(
            model_name='recordmedia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('visibility', 'approved_public_case'), _negated=True), models.Q(('consent_confirmed', True), ('public_case__isnull', False)), _connector='OR'), name='record_media_public_case_requires_consent_and_case'),
        ),
    ]
