# Generated by Django 5.2.15 on 2026-08-31 05:15

import apps.records.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def require_explicit_legacy_public_case_cleanup(apps, schema_editor):
    public_case_model = apps.get_model("records", "PublicCase")
    record_media_model = apps.get_model("records", "RecordMedia")

    related_case_count = public_case_model.objects.filter(
        models.Q(patient_id__isnull=False) | models.Q(reference_visit_id__isnull=False)
    ).count()
    attached_media_count = record_media_model.objects.filter(
        public_case_id__isnull=False
    ).count()
    approved_medical_media_count = record_media_model.objects.filter(
        visibility="approved_public_case"
    ).count()

    if related_case_count or attached_media_count or approved_medical_media_count:
        raise RuntimeError(
            "Public-case domain separation stopped safely because legacy linked data still "
            "exists. Explicitly export/migrate and clean the legacy rows before retrying "
            f"(patient/reference PublicCase rows={related_case_count}, "
            f"RecordMedia attached to PublicCase={attached_media_count}, "
            f"APPROVED_PUBLIC_CASE RecordMedia rows={approved_medical_media_count}). "
            "No legacy relationship or medical-media publication state was discarded."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_gender'),
        ('records', '0007_publiccase_detail_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            require_explicit_legacy_public_case_cleanup,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='PatientTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('public_case_published', 'Public case published')], db_index=True, default='public_case_published', max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicCaseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('before', 'Before'), ('after', 'After'), ('video', 'Video'), ('video_cover', 'Video cover')], db_index=True, max_length=20)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('short_video', 'Short video')], max_length=20)),
                ('file', models.FileField(storage=apps.records.storage.PublicCaseMediaStorage(), upload_to=apps.records.storage.public_case_media_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('consent_confirmed', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='recordmedia',
            name='record_media_public_case_requires_consent_and_case',
        ),
        migrations.RemoveIndex(
            model_name='recordmedia',
            name='records_rec_visibil_de2be1_idx',
        ),
        migrations.RemoveField(
            model_name='publiccase',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='publiccase',
            name='reference_visit',
        ),
        migrations.RemoveField(
            model_name='recordmedia',
            name='consent_confirmed',
        ),
        migrations.RemoveField(
            model_name='recordmedia',
            name='public_case',
        ),
        migrations.RemoveField(
            model_name='recordmedia',
            name='public_case_role',
        ),
        migrations.AlterField(
            model_name='recordmedia',
            name='visibility',
            field=models.CharField(choices=[('private_only', 'Private only'), ('visible_to_patient', 'Visible to patient')], db_index=True, default='private_only', max_length=30),
        ),
        migrations.AddIndex(
            model_name='recordmedia',
            index=models.Index(fields=['visibility', 'is_active'], name='records_rec_visibil_07176c_idx'),
        ),
        migrations.AddField(
            model_name='patienttimelineevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patienttimelineevent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_events', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='publiccasemedia',
            name='public_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='records.publiccase'),
        ),
        migrations.AddField(
            model_name='publiccasemedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_case_media_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patienttimelineevent',
            index=models.Index(fields=['patient', 'occurred_at'], name='records_pat_patient_cca05b_idx'),
        ),
        migrations.AddIndex(
            model_name='publiccasemedia',
            index=models.Index(fields=['public_case', 'uploaded_at'], name='records_pub_public__ed6cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='publiccasemedia',
            index=models.Index(fields=['role', 'consent_confirmed', 'is_active'], name='records_pub_role_f6d376_idx'),
        ),
    ]
