"""Root URL configuration for Dr. Khaled Badran Clinic."""

from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

from apps.booking import views as booking_views
from apps.core import review_views, views
from apps.patients import views as patient_views


urlpatterns = [
    path("", views.home, {"language": "ar"}, name="home"),
    path("login/", patient_views.portal_login, {"language": "ar"}, name="login"),
    path("doctor/", views.doctor_profile, {"language": "ar"}, name="doctor"),
    path("services/", views.services, {"language": "ar"}, name="services"),
    path("cases/", views.public_cases, {"language": "ar"}, name="public_cases"),
    path("reviews/", review_views.reviews, {"language": "ar"}, name="reviews"),
    path(
        "cases/media/<uuid:public_id>/",
        views.public_case_media,
        {"language": "ar"},
        name="public_case_media",
    ),
    path("contact-location/", views.contact, {"language": "ar"}, name="contact"),
    path(
        "contact/",
        RedirectView.as_view(pattern_name="contact", permanent=True, query_string=True),
        name="contact_legacy",
    ),
    path("book/", booking_views.book_start, {"language": "ar"}, name="book"),
    path(
        "book/visit-type/",
        booking_views.select_visit_type,
        {"language": "ar"},
        name="booking_visit_type",
    ),
    path("book/slots/", booking_views.select_slot, {"language": "ar"}, name="booking_slots"),
    path(
        "book/confirm/",
        booking_views.confirm_booking,
        {"language": "ar"},
        name="booking_confirm",
    ),
    path(
        "book/success/<uuid:public_token>/",
        booking_views.booking_success,
        {"language": "ar"},
        name="booking_success",
    ),
    path("privacy/", views.privacy, {"language": "ar"}, name="privacy"),
    path("terms/", views.terms, {"language": "ar"}, name="terms"),
    path(
        "medical-disclaimer/",
        views.medical_disclaimer,
        {"language": "ar"},
        name="medical_disclaimer",
    ),
    path(
        "whatsapp-policy/",
        views.whatsapp_policy,
        {"language": "ar"},
        name="whatsapp_policy",
    ),
    path("en/", views.home, {"language": "en"}, name="home_en"),
    path("en/login/", patient_views.portal_login, {"language": "en"}, name="login_en"),
    path("en/doctor/", views.doctor_profile, {"language": "en"}, name="doctor_en"),
    path("en/services/", views.services, {"language": "en"}, name="services_en"),
    path("en/cases/", views.public_cases, {"language": "en"}, name="public_cases_en"),
    path("en/reviews/", review_views.reviews, {"language": "en"}, name="reviews_en"),
    path(
        "en/cases/media/<uuid:public_id>/",
        views.public_case_media,
        {"language": "en"},
        name="public_case_media_en",
    ),
    path("en/contact-location/", views.contact, {"language": "en"}, name="contact_en"),
    path(
        "en/contact/",
        RedirectView.as_view(pattern_name="contact_en", permanent=True, query_string=True),
        name="contact_legacy_en",
    ),
    path("en/book/", booking_views.book_start, {"language": "en"}, name="book_en"),
    path(
        "en/book/visit-type/",
        booking_views.select_visit_type,
        {"language": "en"},
        name="booking_visit_type_en",
    ),
    path(
        "en/book/slots/",
        booking_views.select_slot,
        {"language": "en"},
        name="booking_slots_en",
    ),
    path(
        "en/book/confirm/",
        booking_views.confirm_booking,
        {"language": "en"},
        name="booking_confirm_en",
    ),
    path(
        "en/book/success/<uuid:public_token>/",
        booking_views.booking_success,
        {"language": "en"},
        name="booking_success_en",
    ),
    path("staff/appointments/", booking_views.staff_appointment_list, name="staff_appointment_list"),
    path(
        "staff/appointments/<int:appointment_id>/",
        booking_views.staff_appointment_detail,
        name="staff_appointment_detail",
    ),
    path(
        "staff/appointments/<int:appointment_id>/cancel/",
        booking_views.staff_appointment_cancel,
        name="staff_appointment_cancel",
    ),
    path(
        "staff/appointments/<int:appointment_id>/reschedule/",
        booking_views.staff_appointment_reschedule,
        name="staff_appointment_reschedule",
    ),
    path(
        "staff/appointments/<int:appointment_id>/arrived/",
        booking_views.staff_appointment_arrived,
        name="staff_appointment_arrived",
    ),
    path(
        "staff/appointments/<int:appointment_id>/complete/",
        booking_views.staff_appointment_complete,
        name="staff_appointment_complete",
    ),
    path(
        "staff/appointments/<int:appointment_id>/no-show/",
        booking_views.staff_appointment_no_show,
        name="staff_appointment_no_show",
    ),
    path("en/privacy/", views.privacy, {"language": "en"}, name="privacy_en"),
    path("en/terms/", views.terms, {"language": "en"}, name="terms_en"),
    path(
        "en/medical-disclaimer/",
        views.medical_disclaimer,
        {"language": "en"},
        name="medical_disclaimer_en",
    ),
    path(
        "en/whatsapp-policy/",
        views.whatsapp_policy,
        {"language": "en"},
        name="whatsapp_policy_en",
    ),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("sitemap.xml", views.sitemap_xml, name="sitemap_xml"),
    path("health/", views.health_check, name="health"),
    path("health/ready/", views.readiness_check, name="health_ready"),
    path("dashboard/", include("apps.dashboard.urls")),
    path("records/", include("apps.records.urls")),
    path("portal/", patient_views.portal_dashboard, {"language": "ar"}, name="patient_portal_dashboard"),
    path("portal/login/", patient_views.portal_login, {"language": "ar"}, name="patient_portal_login"),
    path("portal/logout/", patient_views.portal_logout, {"language": "ar"}, name="patient_portal_logout"),
    path("portal/register/", patient_views.portal_register, {"language": "ar"}, name="patient_portal_register"),
    path("portal/account/", patient_views.portal_account, {"language": "ar"}, name="patient_portal_account"),
    path(
        "portal/password/change/",
        patient_views.portal_password_change,
        {"language": "ar"},
        name="patient_portal_password_change",
    ),
    path(
        "portal/account-recovery/",
        patient_views.portal_account_recovery,
        {"language": "ar"},
        name="patient_portal_account_recovery",
    ),
    path(
        "portal/link-appointment/",
        patient_views.portal_link_appointment,
        {"language": "ar"},
        name="patient_portal_link_appointment",
    ),
    path(
        "portal/appointments/",
        patient_views.portal_appointment_list,
        {"language": "ar"},
        name="patient_portal_appointment_list",
    ),
    path(
        "portal/medical-records/",
        patient_views.patient_portal_medical_records,
        {"language": "ar"},
        name="patient_portal_medical_records",
    ),
    path(
        "portal/medical-records/media/<uuid:public_id>/download/",
        patient_views.patient_portal_medical_record_media_download,
        {"language": "ar"},
        name="patient_portal_medical_record_media_download",
    ),
    path(
        "portal/appointments/<uuid:public_token>/",
        patient_views.portal_appointment_detail,
        {"language": "ar"},
        name="patient_portal_appointment_detail",
    ),
    path("en/portal/", patient_views.portal_dashboard, {"language": "en"}, name="patient_portal_dashboard_en"),
    path("en/portal/login/", patient_views.portal_login, {"language": "en"}, name="patient_portal_login_en"),
    path("en/portal/logout/", patient_views.portal_logout, {"language": "en"}, name="patient_portal_logout_en"),
    path("en/portal/register/", patient_views.portal_register, {"language": "en"}, name="patient_portal_register_en"),
    path("en/portal/account/", patient_views.portal_account, {"language": "en"}, name="patient_portal_account_en"),
    path(
        "en/portal/password/change/",
        patient_views.portal_password_change,
        {"language": "en"},
        name="patient_portal_password_change_en",
    ),
    path(
        "en/portal/account-recovery/",
        patient_views.portal_account_recovery,
        {"language": "en"},
        name="patient_portal_account_recovery_en",
    ),
    path(
        "en/portal/link-appointment/",
        patient_views.portal_link_appointment,
        {"language": "en"},
        name="patient_portal_link_appointment_en",
    ),
    path(
        "en/portal/appointments/",
        patient_views.portal_appointment_list,
        {"language": "en"},
        name="patient_portal_appointment_list_en",
    ),
    path(
        "en/portal/medical-records/",
        patient_views.patient_portal_medical_records,
        {"language": "en"},
        name="patient_portal_medical_records_en",
    ),
    path(
        "en/portal/medical-records/media/<uuid:public_id>/download/",
        patient_views.patient_portal_medical_record_media_download,
        {"language": "en"},
        name="patient_portal_medical_record_media_download_en",
    ),
    path(
        "en/portal/appointments/<uuid:public_token>/",
        patient_views.portal_appointment_detail,
        {"language": "en"},
        name="patient_portal_appointment_detail_en",
    ),
    path("admin/", admin.site.urls),
]

handler404 = "apps.core.views.public_404"
