# Generated by Django 5.2.15 on 2026-06-28 20:56

import apps.booking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='confirmed', max_length=20)),
                ('reminder_offset', models.DurationField(default=apps.booking.models.default_appointment_reminder_offset)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('booking_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.visittype')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], max_length=20)),
                ('new_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='booking.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'starts_at'], name='booking_app_doctor__a47ee3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'starts_at'], name='booking_app_patient_648c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'starts_at'], name='booking_app_status_40b6e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='appointment_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='appointmentstatushistory',
            index=models.Index(fields=['appointment', 'created_at'], name='booking_app_appoint_8f544b_idx'),
        ),
    ]
