# Generated by Django 5.2.15 on 2026-06-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_public_token_and_constraints'),
        ('clinic', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status', 'starts_at'], name='booking_app_doctor__2b7f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['starts_at'], name='booking_app_starts__d7d392_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'arrived', 'rescheduled'])), fields=('doctor', 'starts_at'), name='unique_active_appointment_doctor_start'),
        ),
    ]
