# Generated by Django 5.2.15 on 2026-09-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_booking_app_doctor__2b7f9b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact_phone_e164',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_phone_raw',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='whatsapp_phone_e164',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='whatsapp_phone_raw',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
