# Generated by Django 5.2.15 on 2026-06-28 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_raw', models.CharField(max_length=50)),
                ('phone_e164', models.CharField(blank=True, max_length=20)),
                ('whatsapp_phone_raw', models.CharField(blank=True, max_length=50)),
                ('whatsapp_phone_e164', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['phone_raw'], name='patients_pa_phone_r_d0266d_idx'), models.Index(fields=['phone_e164'], name='patients_pa_phone_e_4cba33_idx')],
            },
        ),
    ]
