# Generated by Django 5.2.15 on 2026-09-03 05:15

import apps.patients.storage
import apps.records.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('new', 'New'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('staff_reply', models.TextField(blank=True, max_length=5000)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_replied', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(storage=apps.records.storage.PrivateMediaStorage(), upload_to=apps.patients.storage.consultation_attachment_upload_path)),
                ('file_category', models.CharField(choices=[('image', 'Image'), ('short_video', 'Short video'), ('pdf', 'PDF')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.consultation')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountPhoneChangeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('phone_raw', models.CharField(max_length=50)),
                ('phone_e164', models.CharField(db_index=True, max_length=20)),
                ('otp_digest', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('last_sent_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_phone_change_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'consumed_at', 'expires_at'], name='patients_ac_user_id_5b4096_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient', 'created_at'], name='patients_co_patient_3c2cee_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status', 'created_at'], name='patients_co_status_2931d9_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationattachment',
            index=models.Index(fields=['consultation', 'uploaded_at'], name='patients_co_consult_15d439_idx'),
        ),
    ]
