# Generated by Django 5.2.15 on 2026-09-09 09:13

import apps.patients.models
import apps.patients.storage
import apps.records.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_consultationnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransientConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone_e164', models.CharField(max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('question', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('new', 'New'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('staff_reply', models.TextField(blank=True, max_length=5000)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('staff_handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transient_consultations_replied', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransientConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(storage=apps.records.storage.PrivateMediaStorage(), upload_to=apps.patients.storage.consultation_attachment_upload_path)),
                ('file_category', models.CharField(choices=[('image', 'Image'), ('short_video', 'Short video'), ('pdf', 'PDF')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.transientconsultation')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
            bases=(apps.patients.models.ConsultationAttachmentPolicy, models.Model),
        ),
        migrations.CreateModel(
            name='TransientConsultationAudioReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(storage=apps.records.storage.PrivateMediaStorage(), upload_to=apps.patients.storage.consultation_audio_reply_upload_path)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_reply', to='patients.transientconsultation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transient_audio_replies_created', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(apps.patients.models.ConsultationAudioPolicy, models.Model),
        ),
        migrations.CreateModel(
            name='TransientConsultationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_digest', models.CharField(db_index=True, max_length=64)),
                ('phone_e164', models.CharField(max_length=20)),
                ('otp_digest', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('grant_expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_challenges', to='patients.transientconsultation')),
            ],
        ),
    ]
