# Generated by Django 5.2.15 on 2026-09-11 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_transient_consultations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('recovery', 'Recovery')], max_length=12)),
                ('session_digest', models.CharField(max_length=64)),
                ('phone_e164', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=2)),
                ('otp_digest', models.CharField(blank=True, max_length=128)),
                ('pending_registration', models.JSONField(blank=True, default=dict)),
                ('credential_digest', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('grant_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
