from django.urls import path

from . import views


urlpatterns = [
    path("", views.dashboard_home, name="dashboard_home"),
    path("scheduling/", views.dashboard_scheduling, name="dashboard_scheduling"),
    path(
        "scheduling/weekly/create/",
        views.dashboard_scheduling_weekly_create,
        name="dashboard_scheduling_weekly_create",
    ),
    path(
        "scheduling/weekly/<int:period_id>/update/",
        views.dashboard_scheduling_weekly_update,
        name="dashboard_scheduling_weekly_update",
    ),
    path(
        "scheduling/weekly/<int:period_id>/deactivate/",
        views.dashboard_scheduling_weekly_deactivate,
        name="dashboard_scheduling_weekly_deactivate",
    ),
    path(
        "scheduling/special-hours/create/",
        views.dashboard_scheduling_special_create,
        name="dashboard_scheduling_special_create",
    ),
    path(
        "scheduling/special-hours/<int:period_id>/update/",
        views.dashboard_scheduling_special_update,
        name="dashboard_scheduling_special_update",
    ),
    path(
        "scheduling/special-hours/<int:period_id>/deactivate/",
        views.dashboard_scheduling_special_deactivate,
        name="dashboard_scheduling_special_deactivate",
    ),
    path(
        "scheduling/special-hours/use-weekly/",
        views.dashboard_scheduling_special_use_weekly,
        name="dashboard_scheduling_special_use_weekly",
    ),
    path(
        "scheduling/closures/create/",
        views.dashboard_scheduling_closure_create,
        name="dashboard_scheduling_closure_create",
    ),
    path(
        "scheduling/closures/<int:closure_id>/deactivate/",
        views.dashboard_scheduling_closure_deactivate,
        name="dashboard_scheduling_closure_deactivate",
    ),
    path(
        "scheduling/services/create/",
        views.dashboard_scheduling_service_create,
        name="dashboard_scheduling_service_create",
    ),
    path(
        "scheduling/services/<int:visit_type_id>/duration/",
        views.dashboard_scheduling_service_duration,
        name="dashboard_scheduling_service_duration",
    ),
    path(
        "scheduling/services/<int:visit_type_id>/deactivate/",
        views.dashboard_scheduling_service_deactivate,
        name="dashboard_scheduling_service_deactivate",
    ),
    path(
        "scheduling/services/<int:visit_type_id>/reactivate/",
        views.dashboard_scheduling_service_reactivate,
        name="dashboard_scheduling_service_reactivate",
    ),
    path(
        "scheduling/rules/update/",
        views.dashboard_scheduling_rules_update,
        name="dashboard_scheduling_rules_update",
    ),
    path("patients/", views.dashboard_patient_list, name="dashboard_patient_list"),
    path(
        "patients/<int:patient_id>/records/",
        views.dashboard_patient_record_detail,
        name="dashboard_patient_record_detail",
    ),
    path(
        "patients/<int:patient_id>/records/visits/new/",
        views.dashboard_visit_create,
        name="dashboard_visit_create",
    ),
    path(
        "patients/<int:patient_id>/records/notes/new/",
        views.dashboard_note_create,
        name="dashboard_note_create",
    ),
    path(
        "patients/<int:patient_id>/records/media/new/",
        views.dashboard_media_create,
        name="dashboard_media_create",
    ),
    path(
        "patients/<int:patient_id>/records/media-folders/create/",
        views.dashboard_media_folder_create,
        name="dashboard_media_folder_create",
    ),
    path(
        "patients/<int:patient_id>/records/media-folders/<int:folder_id>/rename/",
        views.dashboard_media_folder_rename,
        name="dashboard_media_folder_rename",
    ),
    path(
        "patients/<int:patient_id>/records/media-folders/<int:folder_id>/delete/",
        views.dashboard_media_folder_delete,
        name="dashboard_media_folder_delete",
    ),
    path(
        "patients/<int:patient_id>/records/public-case/create/",
        views.dashboard_public_case_create,
        name="dashboard_public_case_create",
    ),
    path(
        "patients/<int:patient_id>/records/media/<uuid:public_id>/edit/",
        views.dashboard_media_update,
        name="dashboard_media_update",
    ),
]
