# Generated by Django 5.2.15 on 2026-06-28 20:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name_ar', models.CharField(default='عيادة الدكتور خالد بدران', max_length=255)),
                ('official_name_en', models.CharField(default='Dr. Khaled Badran Clinic', max_length=255)),
                ('phone_raw', models.CharField(blank=True, max_length=50)),
                ('address_ar', models.TextField(blank=True)),
                ('address_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['official_name_en'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ar', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=80)),
                ('title_en', models.CharField(blank=True, max_length=80)),
                ('specialty_ar', models.CharField(blank=True, max_length=255)),
                ('specialty_en', models.CharField(blank=True, max_length=255)),
                ('bio_ar', models.TextField(blank=True)),
                ('bio_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'full_name_en'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('show_price_to_patient', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions_ar', models.TextField(blank=True)),
                ('instructions_en', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_types', to='clinic.doctor')),
            ],
            options={
                'ordering': ['display_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason_ar', models.CharField(blank=True, max_length=255)),
                ('reason_en', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_days', to='clinic.doctor')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='clinic_clos_date_e31ff7_idx'), models.Index(fields=['doctor', 'date'], name='clinic_clos_doctor__cd8cc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic.doctor')),
            ],
            options={
                'ordering': ['doctor', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['doctor', 'weekday', 'is_active'], name='clinic_doct_doctor__62dcdb_idx')],
            },
        ),
    ]
