# Generated by Django 5.2.15 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("reason_ar", models.CharField(blank=True, max_length=255)),
                ("reason_en", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to="clinic.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["doctor", "date", "start_time", "id"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "date", "is_active"],
                        name="clinic_ovr_doc_date_active_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="clinic_override_end_after_start",
                    )
                ],
            },
        ),
    ]
